# Generated by Django 2.1.3 on 2019-05-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author2book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='author2book',
            old_name='book_id',
            new_name='book',
        ),
    ]
