# Generated by Django 2.1.3 on 2019-05-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wenjie', '0003_auto_20190514_0708'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='wenjie_person_new',
        ),
    ]
