# Generated by Django 2.1.3 on 2019-05-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wenjie', '0004_auto_20190514_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hobby', models.CharField(max_length=32)),
                ('phone', models.IntegerField()),
                ('addr', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
        migrations.AddField(
            model_name='author',
            name='detail',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wenjie.AuthorDetail'),
        ),
    ]
