# Generated by Django 2.1.3 on 2019-05-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wenjie', '0005_auto_20190516_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='detail',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='wenjie.AuthorDetail'),
            preserve_default=False,
        ),
    ]
