# Generated by Django 2.1.3 on 2019-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
