# Generated by Django 2.1.3 on 2019-05-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20190507_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
