# Generated by Django 2.1.3 on 2019-05-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_publisher_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
