# Generated by Django 2.1.3 on 2019-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20190508_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('book', models.ManyToManyField(to='app01.Book')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
